services:
  app:
    image: lilkhalil/blog:latest
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/blog
    depends_on:
      - database
  database:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: