spring:
  application:
    name: blog
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true