spring:
  application:
    name: blog
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update